# Generated by Django 5.1.3 on 2024-11-25 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('correo_electronico', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberia_app.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Barbero',
                'verbose_name_plural': 'Barberos',
                'db_table': 'barbero',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=30, verbose_name='Nombre del Cliente')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('dia_hora', models.DateTimeField(verbose_name='Día y Hora')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total')),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberia_app.barbero', verbose_name='Barbero')),
                ('servicios', models.ManyToManyField(to='barberia_app.servicio', verbose_name='Servicios')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'db_table': 'formulario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberia_app.barbero', verbose_name='Barbero')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberia_app.formulario', verbose_name='Formulario')),
                ('servicios', models.ManyToManyField(to='barberia_app.servicio', verbose_name='Servicios')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'cita',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto')),
                ('metodo', models.CharField(max_length=20, verbose_name='Método')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberia_app.cita', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['id'],
            },
        ),
    ]
