# Generated by Django 5.1.3 on 2024-11-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbero',
            name='especialidad',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='correo'),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
