# Generated by Django 5.1.3 on 2024-11-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia_app', '0002_remove_barbero_especialidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='barbero',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='correo Eletronico'),
        ),
    ]
