# Generated by Django 5.1.3 on 2024-11-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia_app', '0003_remove_formulario_barbero_alter_formulario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='formulario',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
